(install) fix circular reference that defeats perl's GC
else we keep the RPM DB open several times until rpm fails:

created transaction for installing on / (remove=0, install=0, upgrade=8)
error: rpmdb: Lock table is out of available locker entries
error: cannot open Basenames index using db4 - Cannot allocate memory (12)
error: rpmdb: Lock table is out of available locker entries
error: cannot open Group index using db4 - Cannot allocate memory (12)
error: rpmdb: Lock table is out of available locker entries
error: cannot open Requirename index using db4 - Cannot allocate memory (12)
error: rpmdb: Lock table is out of available locker entries
error: cannot open Triggername index using db4 - Cannot allocate memory (12)
error: rpmdb: Lock table is out of available locker entries
(...)

regression introduced in commit r2946 on 2012-02-14
(was: '(install) --test: do not display "More information on package"')