fix a testsuite warning
Explicitely adding libnss3.so fixes installing that package:
warning: %post(rpm-query-in-scriptlet-1-1.x86_64) scriptlet failed, exit status 127

Which is b/c of:
error: Failed to initialize NSS library